//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyHangHoa
{
    using System;
    using System.Collections.Generic;
    
    public partial class HangTonKho
    {
        public int MaHangHoa { get; set; }
        public Nullable<int> SoLuongCon { get; set; }
    
        public virtual HangHoa HangHoa { get; set; }
    }
}
