//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyHangHoa
{
    using System;
    using System.Collections.Generic;
    
    public partial class HangHoa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HangHoa()
        {
            this.PhieuNhapHangs = new HashSet<PhieuNhapHang>();
        }
    
        public int MaHangHoa { get; set; }
        public Nullable<int> MaMatHang { get; set; }
        public Nullable<int> MaNhaCungCap { get; set; }
        public Nullable<int> MaQuiCach { get; set; }
        public Nullable<int> MaDonViTinh { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public Nullable<int> MaDanhMuc { get; set; }
    
        public virtual DonViTinh DonViTinh { get; set; }
        public virtual MatHang MatHang { get; set; }
        public virtual NhaCungCap NhaCungCap { get; set; }
        public virtual QuiCach QuiCach { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuNhapHang> PhieuNhapHangs { get; set; }
        public virtual DanhMuc DanhMuc { get; set; }
    }
}
